
###
GET http://localhost:3000/cadastro/unidade
X-API-Key:123456

###
GET http://localhost:3000/cadastro/unidade/paginated?page=1&limit=10
X-API-Key:123456

###
POST http://localhost:3000/cadastro/unidade
content-type: application/json
X-API-Key:123456

{
    "Nome": "Unidade_04",
    "Email":"teste@testes.com",
    "Cnpj":"25158545000151"
}

###
GET http://localhost:3000/cadastro/unidade/d0rgrfagqv14sr3radcg
X-API-Key:123456


###
POST http://localhost:3000/cadastro/unidade/aggregate
content-type: application/json
X-API-Key:123456

{
    "Nome": "Unidade_06_aggregate",
    "Email":"teste@testes.com",
    "contatos":[
        {
        "nome":"Contato 07",
        "email":"caonto@teste.com"
        },
        {
        "nome":"Contato 08",
        "email":"caonto@teste.com"
        }
    ]
}


