
###
GET http://localhost:3000/cadastro/unidade
X-API-Key:123456

###
POST http://localhost:3000/cadastro/unidade
content-type: application/json

{
    "Nome": "sample",
    "Email":"teste@testes.com"
}

###
GET http://localhost:3000/cadastro/unidade/10



